Repository bratislava/paas-mpa, pull requests merged in 2023-11, with the labels that each got.

#146 feat/#144: implement verification result screens
  app/auth.tsx
  app/confirm-signin.tsx
  app/confirm-signup.tsx
  app/parking-cards/[email].tsx
  app/parking-cards/index.tsx
  app/parking-cards/verification/index.tsx
  app/parking-cards/verification/verification-result.tsx
  app/parking-cards/verification/verification-sent.tsx
  components/inputs/Autocomplete.tsx
  components/parking-cards/EmailsBottomSheet.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#147 #101: Refetch on refocus
  app/(purchase-and-payment)/purchase/index.tsx
  app/_layout.tsx
  app/parking-cards/[email].tsx
  app/parking-cards/index.tsx
  app/tickets/index.tsx
  components/controls/notifications/NotificationSettings.tsx
  components/controls/payment-methods/VisitorCardsField.tsx
  components/map/MapZoneBottomSheetAttachment.tsx
  components/screen-layout/Snackbar/Snackbar.tsx
  components/special/AxiosResponseInterceptors.tsx
  components/special/OmnipresentComponent.tsx
  hooks/useQueryWithFocusRefetch.ts
  modules/arcgis/hooks/useStaticArcgisData.ts
  modules/backend/hooks/useAxiosResponseInterceptors.ts
Labels: pr: fix & ship :ship:

#150 #107: Announcements
  app/announcements/index.tsx
  app/index.tsx
  components/info/Announcement.tsx
  components/info/AvatarSquare.tsx
  components/info/SeveritySquare.tsx
  components/shared/Markdown.tsx
  markdown.d.ts
  modules/backend/constants/queryOptions.ts
  modules/backend/hooks/useLastReadAnnouncementIdStorage.ts
  modules/backend/hooks/usePrefetchOnAppStart.tsx
  package.json
  tailwind.config.js
  translations/en.json
  translations/sk.json
  tsconfig.json
  yarn.lock
Labels: pr: fix & ship :ship:

#151 fix registration process to updated setup in Cognito
  app/confirm-signin.tsx
  app/confirm-signup.tsx
  components/screen-layout/Snackbar/Snackbar.tsx
  hooks/useSignInOrSignUp.ts
  modules/backend/axios-instance.ts
  modules/backend/hooks/useAxiosResponseInterceptors.ts
  modules/backend/hooks/usePrefetchOnAppStart.tsx
  modules/cognito/amplify.ts
  modules/cognito/utils.ts
  utils/errors.ts
Labels: pr: fix & ship :ship:

#152 Feat/#16 code input
  app/confirm-signin.tsx
  app/examples/codeinput-example.tsx
  app/parking-cards/verification/index.tsx
  app/parking-cards/verification/verification-result.tsx
  app/parking-cards/verification/verification-sent.tsx
  components/DeveloperMenu.tsx
  components/inputs/CodeInput.tsx
  components/tickets/PurchaseBottomSheet.tsx
  modules/backend/openapi-generated/api.ts
  package.json
  yarn.lock
Labels: pr: needs review :pray:

#153 use new duration in seconds, remove tinyduration
  components/controls/payment-methods/PaymentMethodsFieldControl.tsx
  components/controls/payment-methods/VisitorCardsField.tsx
  components/tickets/PurchaseBottomSheet.tsx
  package.json
  utils/formatBalance.ts
  utils/formatPeriodOfTime.ts
  yarn.lock
Labels: pr: needs review :pray:

#155 feat: show cards restrictions info, update api
  app/(purchase-and-payment)/purchase/index.tsx
  app/announcements/index.tsx
  app/index.tsx
  components/controls/payment-methods/BonusCardMethod.tsx
  components/controls/payment-methods/VisitorCardMethod.tsx
  components/tickets/PurchaseBottomSheet.tsx
  components/tickets/TicketCard.tsx
  modules/backend/constants/queryOptions.ts
  modules/backend/hooks/usePrefetchOnAppStart.tsx
  modules/backend/openapi-generated/api.ts
  modules/map/utils/normalizeZone.ts
Labels: pr: needs review :pray:

#163 update to new payment urls
  components/tickets/PurchaseBottomSheet.tsx
  modules/backend/openapi-generated/api.ts
Labels: pr: needs review :pray:

#164 Fix: quickfix EmptyStateScreen + minor updates
  app/announcements/index.tsx
  app/examples/empty-state-example.tsx
  app/index.tsx
  app/parking-cards/[email].tsx
  app/parking-cards/index.tsx
  app/tickets/index.tsx
  app/zone-details/index.tsx
  components/map/MapZoneBottomSheet.tsx
  components/screen-layout/EmptyStateScreen.tsx
  components/screen-layout/ScreenView.tsx
  modules/backend/openapi-generated/api.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#168 Feat/#167 new payment options
  app/(purchase-and-payment)/payment-methods/index.tsx
  app/(purchase-and-payment)/purchase/choose-payment-method.tsx
  app/(purchase-and-payment)/purchase/index.tsx
  app/index.tsx
  app/payment-options/index.tsx
  assets/payment-options-icons/apple-pay.svg
  assets/payment-options-icons/google-pay.svg
  assets/payment-options-icons/index.ts
  components/controls/date-time/TimeSelector.tsx
  components/controls/payment-methods/MethodsField.tsx
  components/controls/payment-methods/PaymentGateMethod.tsx
  components/controls/payment-methods/PaymentMethodsFieldControl.tsx
  components/controls/payment-methods/PaymentOptionsField.tsx
  components/controls/payment-methods/VisitorCardsField.tsx
  components/controls/payment-methods/rows/BonusCardRow.tsx
  components/controls/payment-methods/rows/PaymentOptionRow.tsx
  components/controls/payment-methods/rows/VisitorCardRow.tsx
  components/controls/payment-methods/types.ts
  components/info/AvatarCircle.tsx
  components/info/AvatarCircleFeedback.tsx
  components/info/AvatarCircleLocationOff.tsx
  components/info/AvatarSquare.tsx
  components/showcases/AvatarShowcase.tsx
  hooks/useDefaultPaymentOption.ts
  state/PurchaseStoreProvider/PurchaseStoreProvider.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#166 #159: Search zones
  components/inputs/Autocomplete.tsx
  components/inputs/TextInput.tsx
  components/map/Map.tsx
  components/map/MapAutocomplete.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  modules/map/hooks/useProcessedArcgisData.ts
  modules/map/types.ts
  modules/map/utils/findPolygonCenter.ts
  translations/en.json
  translations/sk.json
Labels: pr: needs review :pray:

#170 Small improvements
  app/user.tsx
  components/info/AvatarCircle.tsx
  components/map/Map.tsx
  components/map/MapAutocomplete.tsx
  components/parking-cards/EmailsBottomSheet.tsx
  components/screen-layout/Modal/ModalContentWithActions.tsx
  hooks/useSignInOrSignUp.ts
  hooks/useVehiclesStorage.ts
  modules/backend/hooks/useLastReadAnnouncementIdStorage.ts
  modules/cognito/hooks/useSignOut.ts
  modules/cognito/utils.ts
  modules/map/constants.ts
  modules/map/hooks/useMapAutocompleteGetOptions.ts
  modules/map/utils/layer-styles/visitors.ts
  package.json
  state/GlobalStoreProvider/GlobalStoreProvider.tsx
  state/GlobalStoreProvider/useUserMMKVInstance.ts
  translations/en.json
  translations/sk.json
  utils/types.ts
  yarn.lock
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#172 Feat/#160: add About page with links to webview
  app/about/index.tsx
  app/about/webview.tsx
  app/index.tsx
  components/list-rows/ListRow.tsx
  components/list-rows/MenuRow.tsx
  translations/en.json
  translations/sk.json
Labels: pr: needs review :pray:

#178 [#175] implement login/logout button
  app/(auth)/confirm-sign-in.tsx
  app/(auth)/sign-in.tsx
  app/(purchase-and-payment)/purchase/index.tsx
  app/examples/confirm-login.tsx
  app/examples/login.tsx
  app/examples/user.tsx
  app/index.tsx
  app/intro.tsx
  components/list-rows/ActionRow.tsx
  components/list-rows/MenuRow.tsx
  components/navigation/MainMenu/MainMenuBottomSheet.tsx
  components/navigation/MainMenu/NewAnnouncementsBadge.tsx
  hooks/useSignInOrSignUp.ts
  modules/cognito/hooks/useSignOut.ts
  modules/cognito/utils.ts
  package.json
  translations/en.json
  translations/sk.json
  yarn.lock
Labels: pr: fix & ship :ship:

#179 update get tickets request to take new params
  app/tickets/index.tsx
  components/map/MapZoneBottomSheetAttachment.tsx
  modules/backend/constants/queryOptions.ts
  modules/backend/openapi-generated/api.ts
Labels: pr: needs review :pray:

#183 #14: Marketing slider
  app.config.js
  app/intro.tsx
  app/onboarding/index.tsx
  assets/images/marketing-slider/index.ts
  assets/images/marketing-slider/paas_app_ilustracia-114.png
  assets/images/marketing-slider/paas_app_ilustracia-115.png
  assets/images/marketing-slider/paas_app_ilustracia-116.png
  assets/images/marketing-slider/paas_app_ilustracia-117.png
  assets/images/marketing-slider/paas_app_ilustracia-118.png
  assets/images/marketing-slider/paas_app_ilustracia2-113.png
  assets/images/splash.png
  components/DeveloperMenu.tsx
  components/navigation/MarketingTabBar.tsx
  hooks/useIsOnboardingFinished.ts
  modules/cognito/utils.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#184 Translation of JSX components, Infite scroll skeleton
  app/(auth)/sign-in.tsx
  app/parking-cards/[email].tsx
  app/parking-cards/index.tsx
  app/parking-cards/verification/verification-result.tsx
  app/tickets/index.tsx
  components/info/Announcement.tsx
  components/parking-cards/SkeletonParkingCard.tsx
  components/screen-layout/ContentWithAvatar.tsx
  components/shared/Markdown.tsx
  components/tickets/SkeletonTicketCard.tsx
  package.json
  translations/en.json
  translations/sk.json
  yarn.lock
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#185 Improvement project structure and contexts
  app/(app)/(purchase-and-payment)/purchase/choose-payment-method.tsx
  app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
  app/(app)/(purchase-and-payment)/purchase/index.tsx
  app/(app)/(purchase-and-payment)/purchase/payment.tsx
  app/(app)/(purchase-and-payment)/ticket-purchase.tsx
  app/(app)/_layout.tsx
  app/(app)/about/index.tsx
  app/(app)/about/webview.tsx
  app/(app)/announcements/index.tsx
  app/(app)/dev/index.tsx
  app/(app)/examples/bottom-sheet-example.tsx
  app/(app)/examples/codeinput-example.tsx
  app/(app)/examples/empty-state-example.tsx
  app/(app)/examples/healthcheck.tsx
  app/(app)/examples/modal-example.tsx
  app/(app)/examples/snackbar-example.tsx
  app/(app)/examples/styleguide.tsx
  app/(app)/examples/user.tsx
  app/(app)/filters/index.tsx
  app/(app)/index.tsx
  app/(app)/parking-cards/[email].tsx
  app/(app)/parking-cards/index.tsx
  app/(app)/parking-cards/verification/index.tsx
  app/(app)/parking-cards/verification/verification-result.tsx
  app/(app)/parking-cards/verification/verification-sent.tsx
  app/(app)/payment-options/index.tsx
  app/(app)/settings/index.tsx
  app/(app)/settings/language.tsx
  app/(app)/tickets/index.tsx
  app/(app)/vehicles/add-vehicle.tsx
  app/(app)/vehicles/index.tsx
  app/(app)/zone-details/index.tsx
  app/(auth)/confirm-sign-in.tsx
  app/(auth)/sign-in.tsx
  app/(purchase-and-payment)/_layout.tsx
  app/_layout.tsx
  components/controls/payment-methods/PaymentOptionsField.tsx
  components/controls/payment-methods/VisitorCardsField.tsx
  components/map/MapZoneBottomSheet.tsx
  components/navigation/MainMenu/MainMenuBottomSheet.tsx
  components/parking-cards/EmailsBottomSheet.tsx
  hooks/useSignInOrSignUp.ts
  hooks/useVehicles.ts
  hooks/useVehiclesStorage.ts
  modules/backend/hooks/useLastReadAnnouncementIdStorage.ts
  modules/cognito/hooks/useSignOut.ts
  modules/map/hooks/useMapAutocompleteGetOptions.ts
  modules/map/hooks/useProcessedArcgisData.ts
  state/AuthStoreProvider/AuthStoreProvider.tsx
  state/AuthStoreProvider/types.ts
  state/AuthStoreProvider/useAuthStoreContext.ts
  state/AuthStoreProvider/useAuthStoreUpdateContext.ts
  state/AuthStoreProvider/useUserMMKVInstance.ts
  state/GlobalStoreProvider/GlobalStoreProvider.tsx
  state/GlobalStoreProvider/useGlobalStoreContext.ts
  state/MapZonesProvider/MapZonesProvider.tsx
  state/MapZonesProvider/useMapZone.ts
  state/MapZonesProvider/useMapZonesContext.ts
  state/PurchaseStoreProvider/PurchaseStoreProvider.tsx
  state/PurchaseStoreProvider/usePurchaseStoreUpdateContext.ts
Labels: pr: fix & ship :ship:

#200 minor visual fixes
  app/(auth)/sign-in.tsx
  components/inputs/TextInput.tsx
  components/navigation/MainMenu/MainMenuBottomSheet.tsx
Labels: pr: needs review :pray:

#198 #154: Filter tickets
  .eslintrc.js
  app/(app)/_layout.tsx
  app/(app)/examples/styleguide.tsx
  app/(app)/filters/index.tsx
  app/(app)/tickets/filters/index.tsx
  app/(app)/tickets/filters/timeframes.tsx
  app/(app)/tickets/filters/vehicles.tsx
  app/(app)/tickets/index.tsx
  components/inputs/SelectButton.tsx
  components/navigation/ContinueButton.tsx
  components/shared/FloatingButton.tsx
  components/showcases/FloatingButtonShowcase.tsx
  components/showcases/SelectButtonShowcase.tsx
  modules/backend/constants/queryOptions.ts
  state/TicketsFiltersStoreProvider/TicketsFiltersStoreProvider.tsx
  state/TicketsFiltersStoreProvider/useTicketsFiltersStoreContext.ts
  state/TicketsFiltersStoreProvider/useTicketsFiltersStoreUpdateContext.ts
  translations/en.json
  translations/sk.json
  utils/transformTimeframeToFromTo.ts
Labels: pr: fix & ship :ship:

#201 Feature error messages
  app/(app)/(purchase-and-payment)/purchase/index.tsx
  components/tickets/PurchaseBottomSheet.tsx
  modules/backend/hooks/useAxiosResponseInterceptors.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#204 try to improve height of bottom sheets
  app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
  components/controls/vehicles/NoVehicles.tsx
  components/map/MapZoneBottomSheet.tsx
  components/parking-cards/EmailsBottomSheet.tsx
  components/screen-layout/BottomSheet/BottomSheetContent.tsx
  components/screen-layout/ScreenView.tsx
Labels: pr: fix & ship :ship:

#209 fix #117: Skip payment gate when not needed
  app/(app)/(purchase-and-payment)/purchase/index.tsx
  app/(app)/(purchase-and-payment)/purchase/payment.tsx
  components/controls/date-time/TimeSelector.tsx
  components/purchase/PurchaseErrorPanel.tsx
  components/purchase/PurchaseSummaryRow.tsx
  components/screen-layout/BottomSheet/BottomSheetHandleWithShadow.tsx
  components/tickets/PurchaseBottomSheet.tsx
  translations/en.json
  translations/sk.json
  utils/errorPricingApi.ts
  utils/isDefined.ts
Labels: pr: fix & ship :ship:

#208 onboarding text fix and onboarding bottom button fix
  app/onboarding/index.tsx
Labels: pr: fix & ship :ship:

#207 Bugfix keyboard avoiding view
  app/(app)/parking-cards/verification/index.tsx
  app/(app)/parking-cards/verification/verification-sent.tsx
  app/(app)/vehicles/add-vehicle.tsx
  app/(auth)/confirm-sign-in.tsx
  app/(auth)/sign-in.tsx
  components/shared/DissmissKeyboard.tsx
Labels: pr: fix & ship :ship:
