Repository bratislava/paas-mpa, pull requests merged in 2023-09, with the labels that each got.

#5 implement basic components
  .eslintrc.js
  app/examples/styleguide.tsx
  components/action-info/AvatarIcon.tsx
  components/shared/SegmentBadge.tsx
  components/shared/Surface.tsx
  components/shared/Typography.tsx
  components/showcases/AvatarIconShowcase.tsx
  components/showcases/SurfaceShowcase.tsx
  components/showcases/TypographyShowcase.tsx
  tailwind.config.js
Labels: pr: needs review :pray:

#8 init translations with react-i18next
  app/_layout.tsx
  components/showcases/TypographyShowcase.tsx
  hooks/useTranslation.ts
  i18n.config.js
  package.json
  translations/en.json
  translations/index.ts
  translations/sk.json
  yarn.lock
Labels: pr: fix & ship :ship:

#9 init onboarding screens
  .eslintrc.js
  app/_layout.tsx
  app/dev/index.tsx
  app/index.tsx
  app/onboarding/enter-phone-number.tsx
  app/onboarding/enter-verification-code.tsx
  app/onboarding/intro.tsx
  components/DeveloperMenu.tsx
  components/inputs/TextInput.tsx
  components/shared/Button.tsx
  components/shared/ScreenContent.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#20 init "Add payment cards" screens
  .eslintrc.js
  app/_layout.tsx
  app/add-parking-cards/enter-email-addresses.tsx
  app/add-parking-cards/verification-sent.tsx
  app/onboarding/enter-phone-number.tsx
  app/onboarding/enter-verification-code.tsx
  app/onboarding/intro.tsx
  components/DeveloperMenu.tsx
  components/shared/Screen.tsx
  components/shared/ScreenContent.tsx
  hooks/useTranslation.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#25 Install @gorhom/bottom-sheet
  app/examples/bottom-sheet.tsx
  babel.config.js
  components/DeveloperMenu.tsx
  components/shared/Screen.tsx
  package.json
  yarn.lock
Labels: pr: fix & ship :ship:

#28 #26: init Purchase screen
  .eslintrc.js
  app/purchase/index.tsx
  components/DeveloperMenu.tsx
  components/shared/FlexRow.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#32 Feature/#31 save vehicles
  app/add-parking-cards/enter-email-addresses.tsx
  app/add-parking-cards/verification-sent.tsx
  app/examples/bottom-sheet.tsx
  app/onboarding/enter-phone-number.tsx
  app/onboarding/enter-verification-code.tsx
  app/onboarding/intro.tsx
  app/purchase/index.tsx
  app/vehicles/add-vehicle.tsx
  app/vehicles/index.tsx
  components/shared/ScreenContent.tsx
  components/shared/ScreenView.tsx
  hooks/useVehiclesStorage.ts
  package.json
  translations/en.json
  translations/sk.json
  utils/mmkv.ts
  yarn.lock
Labels: pr: fix & ship :ship:

#36 feat: added auto label workflow on PRs
  .github/workflows/label.yml
Labels: pr: fix & ship :ship:

#38 fix: run workflow when user requests a review
  .github/workflows/label.yml
Labels: pr: fix & ship :ship:

#37 Feat/#15 implement Button and Icon
  .eslintrc.js
  app/_layout.tsx
  app/add-parking-cards/verification-sent.tsx
  app/examples/bottom-sheet.tsx
  app/examples/confirm-login.tsx
  app/examples/info.tsx
  app/examples/login.tsx
  app/examples/map.tsx
  app/examples/search.tsx
  app/examples/styleguide.tsx
  app/examples/swiper.tsx
  app/index.tsx
  app/purchase/index.tsx
  app/vehicles/add-vehicle.tsx
  app/vehicles/index.tsx
  components/DeveloperMenu.tsx
  components/action-info/AvatarSquare.tsx
  components/controls/SelectableControl.tsx
  components/info/AvatarCircle.tsx
  components/info/AvatarSquare.tsx
  components/info/SegmentBadge.tsx
  components/shared/Button.tsx
  components/shared/Icon.tsx
  components/shared/ScreenContent.tsx
  components/shared/ScreenView.tsx
  components/shared/Typography.tsx
  components/shared/theme.ts
  components/showcases/AvatarShowcase.tsx
  components/showcases/ButtonShowcase.tsx
  components/showcases/FieldShowcase.tsx
  components/showcases/SegmentBadgeShowcase.tsx
  package.json
  themed.d.ts
  translations/en.json
  translations/sk.json
  tsconfig.json
  yarn.lock
Labels: pr: fix & ship :ship:

#40 Fix/#29 fix add vehicle modal presentation
  app/_layout.tsx
  app/vehicles/_layout.tsx
  app/vehicles/add-vehicle.tsx
  components/DeveloperMenu.tsx
Labels: pr: fix & ship :ship:

#46 #33: improve confirmation modals for vehicle management
  app/examples/modal.tsx
  app/vehicles/add-vehicle.tsx
  app/vehicles/edit-vehicle.tsx
  app/vehicles/index.tsx
  components/shared/Modal.tsx
  hooks/useModal.tsx
  hooks/useVehicles.ts
  translations/en.json
  translations/sk.json
  utils/licencePlate.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#48 Feature #39 payment method components and #47
  app/_layout.tsx
  app/add-parking-cards/enter-email-addresses.tsx
  app/examples/bottom-sheet.tsx
  app/purchase/choose-vehicle.tsx
  app/purchase/index.tsx
  app/vehicles/add-vehicle.tsx
  app/vehicles/index.tsx
  components/controls/SelectableControl.tsx
  components/controls/VehicleControl.tsx
  components/controls/payment-methods/PaymentGate.tsx
  components/controls/vehicles/NoVehicles.tsx
  components/controls/vehicles/VehicleField.tsx
  components/controls/vehicles/VehicleFieldControl.tsx
  components/controls/vehicles/VehicleRow.tsx
  components/info/AvatarSquare.tsx
  components/shared/Panel.tsx
  components/shared/PanelPressable.tsx
  components/shared/Surface.tsx
  components/showcases/DividerShowcase.tsx
  components/showcases/FieldShowcase.tsx
  components/showcases/SurfaceShowcase.tsx
  hooks/useVehicles.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#54 [#51] implement main menu in detached bottom sheet
  .prettierrc.js
  app/index.tsx
  app/parking-cards/enter-paas-account.tsx
  app/parking-cards/index.tsx
  app/parking-cards/verification-sent.tsx
  app/payment-methods/index.tsx
  app/settings/index.tsx
  app/tickets/index.tsx
  app/vehicles/index.tsx
  components/DeveloperMenu.tsx
  components/actions/ActionRow.tsx
  components/shared/BottomSheetContent.tsx
  package.json
  translations/en.json
  translations/sk.json
  yarn.lock
Labels: pr: fix & ship :ship:

#53 Feature/#50 parking cards components, #55 CheckBox
  app/examples/styleguide.tsx
  components/parking-cards/CardContentItem.tsx
  components/parking-cards/ParkingCardBase.tsx
  components/parking-cards/ParkingCardContent.tsx
  components/parking-cards/ResidentCard.tsx
  components/parking-cards/VisitorCard.tsx
  components/shared/CheckBox.tsx
  components/showcases/CheckBoxShowcase.tsx
  components/showcases/ParkingCardsShowcase.tsx
  package.json
  tailwind.config.colors.js
  tailwind.config.js
  translations/en.json
  yarn.lock
Labels: pr: fix & ship :ship:

#61 [#60] implement IconButton and add forwardRef for other components
  app/index.tsx
  components/actions/ActionRow.tsx
  components/controls/payment-methods/PaymentGate.tsx
  components/controls/vehicles/VehicleFieldControl.tsx
  components/controls/vehicles/VehicleRow.tsx
  components/shared/Button.tsx
  components/shared/Icon.tsx
  components/shared/IconButton.tsx
  components/shared/Modal.tsx
  components/showcases/ButtonShowcase.tsx
  components/showcases/ListRowsShowcase.tsx
Labels: pr: fix & ship :ship:

#71 implement PressableStyled and use it always as wrapper where neede
  app/index.tsx
  app/purchase/choose-vehicle.tsx
  app/purchase/index.tsx
  app/vehicles/index.tsx
  components/actions/ActionRow.tsx
  components/controls/payment-methods/PaymentGate.tsx
  components/controls/vehicles/VehicleField.tsx
  components/shared/PanelPressable.tsx
  components/shared/PressableStyled.tsx
  components/showcases/FieldShowcase.tsx
  components/showcases/ListRowsShowcase.tsx
  components/showcases/SurfaceShowcase.tsx
Labels: pr: fix & ship :ship:

#72 feature/#21 dotted background
  assets/images/dotted-background.png
  components/shared/ScreenView.tsx
Labels: pr: fix & ship :ship:

#73 [#27] implement TimeSelector
  app/_layout.tsx
  app/examples/styleguide.tsx
  app/purchase/custom-time.tsx
  app/purchase/index.tsx
  components/controls/TimeSelector.tsx
  components/controls/vehicles/VehicleField.tsx
  components/shared/Chip.tsx
  components/showcases/TimeSelectorShowcase.tsx
  hooks/useTimeSelector.tsx
  tailwind.config.js
  translations/en.json
  translations/sk.json
  utils/formatMinutes.tsx
Labels: pr: fix & ship :ship:

#75 Feature/#22 style nav header
  app/_layout.tsx
  app/index.tsx
  app/purchase/choose-payment-method.tsx
  app/purchase/choose-vehicle.tsx
  app/purchase/index.tsx
  app/vehicles/index.tsx
  components/controls/TimeSelector.tsx
  components/controls/payment-methods/PaymentGate.tsx
  components/controls/vehicles/VehicleField.tsx
  components/controls/vehicles/VehicleFieldControl.tsx
  components/controls/vehicles/VehicleRow.tsx
  components/shared/Button.tsx
  components/shared/IconButton.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#76 Feature/#74 datepicker
  app/index.tsx
  app/purchase/choose-vehicle.tsx
  app/purchase/custom-time.tsx
  app/purchase/index.tsx
  components/controls/date-time/DateTimePicker.tsx
  components/controls/date-time/TimeSelector.tsx
  components/controls/payment-methods/PaymentGate.tsx
  components/controls/vehicles/VehicleRow.tsx
  components/shared/ScrollViewPicker.tsx
  components/showcases/TimeSelectorShowcase.tsx
  package.json
  translations/en.json
  translations/sk.json
  yarn.lock
Labels: pr: fix & ship :ship:

#77 Feature/#62 determine parking zone
  .eslintrc.js
  app/_layout.tsx
  app/examples/map.tsx
  app/index.tsx
  assets/map/index.ts
  assets/map/map-pin-no-zone.svg
  assets/map/map-pin.svg
  components/map/Map.tsx
  components/map/MapPin.tsx
  components/map/MapScreen.tsx
  modules/arcgis/constants.ts
  modules/arcgis/hooks/useArcgis.ts
  modules/arcgis/hooks/useArcgisData.ts
  modules/map/constants.ts
  modules/map/hooks/useLocationPermission.ts
  modules/map/hooks/useProcessedMapData.ts
  modules/map/hooks/useScreenCenter.ts
  modules/map/utils/layer-styles/colors.ts
  modules/map/utils/layer-styles/residents.ts
  modules/map/utils/layer-styles/visitors.ts
  modules/map/utils/layer-styles/visitors2.ts
  modules/map/utils/layer-styles/zones.ts
  modules/map/utils/processData.ts
  package.json
  utils/layer-styles/visitors.ts
  yarn.lock
Labels: pr: fix & ship :ship:

#79 bump expo-router and some outher packages
  app.config.js
  package.json
  yarn.lock
Labels: pr: fix & ship :ship:
