Repository bratislava/paas-mpa, pull requests merged in 2023-12, with the labels that each got.

#225 one time vehicle
  app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
  app/(app)/(purchase-and-payment)/ticket-purchase.tsx
  app/(app)/vehicles/add-vehicle.tsx
  app/(app)/vehicles/index.tsx
  hooks/useVehicles.ts
  hooks/useVehiclesStorage.ts
  state/PurchaseStoreProvider/PurchaseStoreProvider.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#224 #223: Map zone bottom sheet cleanup
  components/map/Map.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  components/map/MapZoneBottomSheetPanel.tsx
  components/map/MapZoneBottomSheetSearch.tsx
  modules/map/hooks/useCameraChangeHandler.ts
  modules/map/hooks/useProcessedArcgisData.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#227 #217: Permissions
  app/(auth)/confirm-sign-in.tsx
  app/onboarding/index.tsx
  app/permissions/index.tsx
  assets/images/permissions/index.ts
  assets/images/permissions/paas_app_ilustracia3-119.png
  assets/images/permissions/paas_app_ilustracia3-120.png
  components/DeveloperMenu.tsx
  components/map/MapLocationBottomSheet.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheetAttachment.tsx
  components/screen-layout/BottomSheet/BottomSheetHandleWithShadow.tsx
  components/screen-layout/InfoSlide.tsx
  hooks/useAppFocusEffect.ts
  modules/map/hooks/useLocation.ts
  modules/map/hooks/useLocationPermission.ts
  modules/map/hooks/useNotificationPermission.ts
  package.json
  translations/en.json
  translations/sk.json
  yarn.lock
Labels: pr: fix & ship :ship:

#228 Feature vehicles api
  app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
  app/(app)/(purchase-and-payment)/purchase/index.tsx
  app/(app)/_layout.tsx
  app/(app)/tickets/filters/vehicles.tsx
  app/(app)/vehicles/add-vehicle.tsx
  app/(app)/vehicles/index.tsx
  components/controls/vehicles/SkeletonVehicleRow.tsx
  components/controls/vehicles/VehicleFieldControl.tsx
  components/controls/vehicles/VehicleRow.tsx
  components/screen-layout/Modal/ModalContentWithActions.tsx
  hooks/useVehicles.ts
  hooks/useVehiclesStorage.ts
  modules/backend/constants/queryOptions.ts
  state/PurchaseStoreProvider/PurchaseStoreProvider.tsx
  state/VehiclesStoreProvider/VehiclesStoreProvider.tsx
  state/VehiclesStoreProvider/useVehiclesStoreContext.ts
  utils/types.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#244 splash screen after user fetch
  app/_layout.tsx
  state/AuthStoreProvider/AuthStoreProvider.tsx
Labels: pr: fix & ship :ship:

#248 displaying confirm-sign-in errors
  app/(auth)/confirm-sign-in.tsx
  components/inputs/CodeInput.tsx
  hooks/useSignInOrSignUp.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#269 [#265] upgrade aws-amplify and implement static login
  app.config.js
  app/(app)/settings/index.tsx
  app/(auth)/confirm-sign-in.tsx
  app/(auth)/sign-in.tsx
  hooks/useSignInOrSignUp.ts
  modules/cognito/amplify.ts
  modules/cognito/hooks/useSignOut.ts
  modules/cognito/utils.ts
  modules/map/hooks/useNotificationPermission.ts
  package.json
  state/AuthStoreProvider/AuthStoreProvider.tsx
  state/AuthStoreProvider/useUserMMKVInstance.ts
  translations/en.json
  translations/sk.json
  utils/errorCognitoAuth.ts
  yarn.lock
Labels: pr: fix & ship :ship:

#287 Feature payment response
  app/(app)/(purchase-and-payment)/purchase/payment.tsx
  app/(app)/(purchase-and-payment)/ticket-purchase.tsx
  modules/backend/openapi-generated/api.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#288 hide DEV and unused menus
  app/(app)/about/index.tsx
  app/(app)/index.tsx
  components/navigation/MainMenu/MainMenuBottomSheet.tsx
Labels: pr: fix & ship :ship:

#289 feat: #264 disable eslint rule react-native/no-inline-styles
  .eslintrc.js
  app/(app)/parking-cards/[email].tsx
  app/(app)/settings/index.tsx
  app/(app)/tickets/index.tsx
  components/controls/date-time/CustomDateTimePicker.tsx
  components/controls/date-time/lib/ScrollViewPicker.tsx
  components/map/MapMarkers.tsx
  components/map/MapZoneBottomSheet.tsx
  components/screen-layout/BottomSheet/BottomSheetHandleWithShadow.tsx
  components/screen-layout/Snackbar/Snackbar.tsx
  components/showcases/ButtonShowcase.tsx
Labels: pr: fix & ship :ship:

#291 check only non-existing users to continue to sing-up
  hooks/useSignInOrSignUp.ts
Labels: pr: fix & ship :ship:

#292 #246: Map search screen
  app/(app)/_layout.tsx
  app/(app)/index.tsx
  app/(app)/search/index.tsx
  components/map/Map.tsx
  components/map/MapAutocomplete.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  components/map/MapZoneBottomSheetAttachment.tsx
  components/map/MapZoneBottomSheetSearch.tsx
  components/navigation/MainMenu/MainMenuBottomSheet.tsx
  modules/map/hooks/useCameraChangeHandler.ts
  modules/map/hooks/useLocation.ts
  modules/map/hooks/useMapAutocompleteGetOptions.ts
  modules/map/types.ts
  modules/map/utils/findShapesInRadius.ts
  modules/map/utils/processData.ts
  modules/map/utils/reverseGeocode.ts
  state/MapSearchProvider/MapSearchProvider.tsx
  state/MapSearchProvider/useMapSearchContext.ts
  state/MapSearchProvider/useMapSearchUpdateContext.ts
  state/MapZonesProvider/types.ts
  state/MapZonesProvider/useMapZone.ts
  translations/en.json
  translations/sk.json
Labels: pr: needs review :pray:

#297 Update en.json
  translations/en.json
Labels: pr: fix & ship :ship:

#296 Update sk.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#299 invalid phone number errors and map page warning
  app/(auth)/confirm-sign-in.tsx
  app/(auth)/sign-in.tsx
  hooks/useSignInOrSignUp.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#298 Main menu screen & bug fixes
  app/(app)/_layout.tsx
  app/(app)/examples/markdown-example.tsx
  app/(app)/index.tsx
  app/(app)/menu.tsx
  app/(app)/parking-cards/index.tsx
  app/(app)/search/index.tsx
  components/DeveloperMenu.tsx
  components/map/Map.tsx
  components/map/MapAutocomplete.tsx
  components/map/MapZoneBottomSheet.tsx
  components/map/MapZoneBottomSheetAttachment.tsx
  components/map/MapZoneBottomSheetPanel.tsx
  components/navigation/MainMenu/MainMenuBottomSheet.tsx
  components/shared/Markdown.tsx
  modules/map/hooks/useCameraChangeHandler.ts
  modules/map/utils/findShapesInRadius.ts
  state/MapSearchProvider/MapSearchProvider.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#310 add proper app icon and splash
  app.config.js
  assets/adaptive-icon.png
  assets/app/adaptive-icon.png
  assets/app/icon.png
  assets/app/splash.png
  assets/icon.png
  assets/images/splash.png
Labels: pr: fix & ship :ship:

#307 Bugfix payment method change
  app/(app)/(purchase-and-payment)/ticket-purchase.tsx
  app/(app)/menu.tsx
  app/(app)/parking-cards/index.tsx
  app/(app)/parking-cards/verification/verification-result.tsx
  app/(app)/parking-cards/verification/verification-sent.tsx
  app/(app)/tickets/filters/index.tsx
  app/(app)/tickets/filters/vehicles.tsx
  app/(app)/tickets/index.tsx
  app/onboarding/index.tsx
  components/list-rows/SelectRow.tsx
  components/tickets/PurchaseBottomContent.tsx
  modules/backend/constants/queryOptions.ts
  modules/backend/openapi-generated/api.ts
  package.json
  state/PurchaseStoreProvider/PurchaseStoreProvider.tsx
  state/TicketsFiltersStoreProvider/TicketsFiltersStoreProvider.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#304 envs in eas build
  .env
  app.config.js
  app/(app)/menu.tsx
  app/(app)/parking-cards/verification/verification-sent.tsx
  app/onboarding/index.tsx
  assets/adaptive-icon.png
  assets/app/adaptive-icon.png
  assets/app/icon.png
  assets/app/splash.png
  assets/icon.png
  assets/images/splash.png
  eas.json
  environment.ts
  modules/backend/client-api.ts
Labels: pr: fix & ship :ship:

#312 Bugfix tickets filtering
  .env
  app/(app)/(purchase-and-payment)/prolongate/[ticketId]/index.tsx
  app/(app)/menu.tsx
  app/(app)/parking-cards/verification/verification-sent.tsx
  app/(app)/tickets/index.tsx
  app/onboarding/index.tsx
  components/controls/date-time/TimeSelector.tsx
  eas.json
  environment.ts
  modules/backend/constants/queryOptions.ts
  modules/backend/openapi-generated/api.ts
Labels: pr: fix & ship :ship:

#318 fix Pay button padding
  app/(app)/menu.tsx
  app/(app)/parking-cards/verification/verification-sent.tsx
  components/tickets/PurchaseBottomContent.tsx
Labels: pr: fix & ship :ship:

#322 Sprint 15 map bug fixes
  components/map/Map.tsx
  components/map/MapAutocomplete.tsx
  components/map/MapPointBottomSheet.tsx
  modules/arcgis/hooks/useArcgisData.ts
  modules/arcgis/hooks/useStaticArcgisData.ts
  modules/arcgis/types.ts
  modules/map/hooks/useCameraChangeHandler.ts
  modules/map/types.ts
  modules/map/utils/normalizePoint.ts
  modules/map/utils/processData.ts
  package.json
  translations/en.json
  translations/sk.json
  yarn.lock
Labels: pr: fix & ship :ship:

#327 parking card errors
  app/(app)/parking-cards/verification/index.tsx
  translations/en.json
  translations/sk.json
  utils/errorService.ts
  utils/isValidEmail.ts
Labels: pr: fix & ship :ship:

#329 #302: Custom compass
  app/(app)/_layout.tsx
  app/(app)/index.tsx
  app/(app)/search/index.tsx
  assets/map/compass.svg
  assets/map/index.ts
  components/map/CompassButton.tsx
  components/map/Map.tsx
  components/map/MapScreen.tsx
  modules/map/hooks/useCameraChangeHandler.ts
  state/MapSearchProvider/MapSearchProvider.tsx
  state/MapSearchProvider/useMapSearchContext.ts
  state/MapSearchProvider/useMapSearchUpdateContext.ts
  state/MapStoreProvider/MapStoreProvider.tsx
  state/MapStoreProvider/useMapStoreContext.ts
  state/MapStoreProvider/useMapStoreUpdateContext.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#334 Feature receipt download
  app/(app)/(purchase-and-payment)/purchase/index.tsx
  app/(app)/parking-cards/[email].tsx
  app/(app)/parking-cards/index.tsx
  app/(app)/parking-cards/verification/verification-result.tsx
  app/(app)/tickets/index.tsx
  components/controls/payment-methods/UsedBonusCard.tsx
  components/controls/payment-methods/VisitorCardsField.tsx
  components/parking-cards/ParkingCard.tsx
  components/parking-cards/cards/BonusCard.tsx
  components/showcases/ParkingCardsShowcase.tsx
  components/tickets/TicketCard.tsx
  hooks/useFirstPurchaseStorage.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#336 Improvement ticket shortening
  app/(app)/tickets/index.tsx
  app/(app)/tickets/shorten/index.tsx
  app/(app)/tickets/shorten/shorten-result.tsx
  components/tickets/TicketCard.tsx
  modules/backend/constants/queryOptions.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#328 #121: Feedback
  app/(app)/feedback/index.tsx
  app/(app)/feedback/success.tsx
  app/(app)/menu.tsx
  components/inputs/TextInput.tsx
  components/screen-layout/Snackbar/useSnackbar.tsx
  components/shared/Field.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:
