Repository bratislava/paas-mpa, pull requests merged in 2023-10, with the labels that each got.

#80 improve and fix purchase screen components and flow
  app/index.tsx
  app/purchase/choose-payment-method.tsx
  app/purchase/choose-vehicle.tsx
  app/purchase/custom-time.tsx
  app/purchase/index.tsx
  app/vehicles/add-vehicle.tsx
  components/controls/date-time/DateTimePicker.tsx
  components/controls/date-time/TimeSelector.tsx
  components/map/MapScreen.tsx
  components/shared/BottomSheetContent.tsx
  components/shared/ScreenContent.tsx
  components/shared/ScreenView.tsx
  utils/formatDuration.ts
  utils/formatMinutes.tsx
  utils/types.ts
Labels: pr: fix & ship :ship:

#81 map icons and bottom sheet
  assets/map/images/assistant.png
  assets/map/images/garage.png
  assets/map/images/index.ts
  assets/map/images/p-plus-r.png
  assets/map/images/parking.png
  assets/map/images/parkomat.png
  assets/map/images/selling-point.png
  components/map/Map.tsx
  components/map/MapMarkers.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  components/map/MapZones.tsx
  declarations.d.ts
  modules/arcgis/hooks/useArcgisData.ts
  modules/map/constants.ts
  modules/map/hooks/useLocation.ts
  modules/map/hooks/useLocationPermission.ts
  modules/map/hooks/useProcessedMapData.ts
  modules/map/types.ts
  modules/map/utils/layer-styles/markers.ts
  modules/map/utils/processData.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#82 Point detail BottomSheet
  app/_layout.tsx
  app/examples/bottom-sheet.tsx
  components/map/Map.tsx
  components/map/MapMarkers.tsx
  components/map/MapPointBottomSheet.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  components/map/NavigateBottomSheetFooter.tsx
  components/shared/Field.tsx
  components/shared/Typography.tsx
  modules/map/constants.ts
  modules/map/types.ts
  modules/map/utils/layer-styles/markers.ts
  modules/map/utils/normalizePoint.ts
  modules/map/utils/processData.ts
  package.json
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#84 init openapi generated axiosClient
  .eslintrc.js
  app/dev/index.tsx
  app/examples/healthcheck.tsx
  app/examples/info.tsx
  app/examples/login.tsx
  app/examples/modal.tsx
  components/DeveloperMenu.tsx
  environment.ts
  modules/backend/axios-instance.ts
  modules/backend/client-api.ts
  modules/backend/openapi-generated/.gitignore
  modules/backend/openapi-generated/.npmignore
  modules/backend/openapi-generated/.openapi-generator-ignore
  modules/backend/openapi-generated/.openapi-generator/FILES
  modules/backend/openapi-generated/.openapi-generator/VERSION
  modules/backend/openapi-generated/api.ts
  modules/backend/openapi-generated/base.ts
  modules/backend/openapi-generated/common.ts
  modules/backend/openapi-generated/configuration.ts
  modules/backend/openapi-generated/git_push.sh
  modules/backend/openapi-generated/index.ts
  modules/backend/utils/fix-client.js
  openapitools.json
  package.json
  utils/amplify.ts
  yarn.lock
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#85 #65: Zone detail screen
  app/_layout.tsx
  app/zone-details/index.tsx
  components/map/Map.tsx
  components/map/MapPointBottomSheet.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  modules/arcgis/hooks/useArcgisData.ts
  modules/map/hooks/useLocation.ts
  modules/map/hooks/useNormalizedPoint.ts
  modules/map/hooks/useProcessedMapData.ts
  modules/map/types.ts
  modules/map/utils/normalizePoint.ts
  modules/map/utils/normalizeZone.ts
  modules/map/utils/processData.ts
  state/GlobalStoreProvider.tsx
  state/hooks/useGlobalStoreContext.ts
  state/hooks/useMapZone.ts
  state/types.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#92 #67: Map filters
  app/filters/index.tsx
  app/index.tsx
  assets/map/active-zones.svg
  assets/map/assistant.svg
  assets/map/garage.svg
  assets/map/images/cluster-circle.png
  assets/map/images/index.ts
  assets/map/index.ts
  assets/map/p-plus-r.svg
  assets/map/parking.svg
  assets/map/parkomat.svg
  assets/map/planned-zones.svg
  assets/map/selling-point.svg
  components/actions/SelectRow.tsx
  components/map/Map.tsx
  components/map/MapMarkers.tsx
  components/map/MapScreen.tsx
  components/map/MapZones.tsx
  components/shared/ScreenView.tsx
  modules/map/constants.ts
  modules/map/hooks/useFilteredMapData.ts
  modules/map/hooks/useProcessedMapData.ts
  modules/map/types.ts
  modules/map/utils/layer-styles/markers.ts
  modules/map/utils/layer-styles/residents.ts
  modules/map/utils/layer-styles/visitors.ts
  modules/map/utils/layer-styles/visitors2.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#94 fix if conditions in registration flow
  app/_layout.tsx
  app/examples/login.tsx
  modules/cognito/amplify.ts
  modules/cognito/utils.ts
  utils/amplify.ts
Labels: pr: fix & ship :ship:

#95 regenerate client
  modules/backend/openapi-generated/api.ts
Labels: pr: fix & ship :ship:

#93 #70 Full text search
  .eslintrc.js
  components/inputs/Autocomplete.tsx
  components/map/Map.tsx
  components/map/MapAutocomplete.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  modules/map/types.ts
  modules/map/utils/forwardGeocode.ts
  modules/map/utils/layer-styles/markers.ts
Labels: pr: fix & ship :ship:

#97 implement Login/Signup and Confirm flow on different pages
  app/auth.tsx
  app/confirm-signin.tsx
  app/confirm-signup.tsx
  app/examples/login.tsx
  app/index.tsx
  app/intro.tsx
  app/onboarding/enter-phone-number.tsx
  app/onboarding/enter-verification-code.tsx
  app/user.tsx
  components/DeveloperMenu.tsx
  components/map/MapScreen.tsx
  modules/backend/axios-instance.ts
  modules/cognito/amplify.ts
  modules/cognito/utils.ts
  state/GlobalStoreProvider.tsx
Labels: pr: fix & ship :ship:

#100 Feature/#99-notification-settings
  app/_layout.tsx
  app/examples/styleguide.tsx
  app/settings/index.tsx
  components/controls/notifications/NotificationControl.tsx
  components/controls/notifications/NotificationSettings.tsx
  components/controls/notifications/SwitchControl.tsx
  components/shared/Switch.tsx
  components/showcases/SwitchShowcase.tsx
  package.json
  translations/en.json
  translations/sk.json
  yarn.lock
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#110 create ticketPriceRequest state in global store
  app/index.tsx
  app/purchase/index.tsx
  components/controls/ParkingZoneControl.tsx
  components/tickets/PurchaseBottomSheet.tsx
  state/GlobalStoreProvider.tsx
  state/types.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#111 Full height search
  app/_layout.tsx
  app/index.tsx
  components/inputs/Autocomplete.tsx
  components/inputs/TextInput.tsx
  components/map/Map.tsx
  components/map/MapAutocomplete.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  hooks/useMultipleRefsSetter.ts
  modules/map/utils/forwardGeocode.ts
  package.json
  tailwind.config.js
  translations/en.json
  translations/sk.json
  yarn.lock
Labels: pr: fix & ship :ship:

#112 #102 Native datetime picker
  app/_layout.tsx
  app/purchase/custom-time.tsx
  components/controls/date-time/CustomDateTimePicker.tsx
  components/controls/date-time/DateTimePicker.tsx
  components/controls/date-time/TimeSelector.tsx
  hooks/useTranslation.ts
  package.json
  yarn.lock
Labels: pr: needs review :pray:

#116 request ticket price
  app/purchase/index.tsx
  app/zone-details/index.tsx
  components/controls/ParkingZoneControl.tsx
  components/controls/ParkingZoneField.tsx
  components/controls/date-time/TimeSelector.tsx
  components/map/MapPin.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  components/tickets/PurchaseBottomSheet.tsx
  modules/backend/openapi-generated/api.ts
  translations/en.json
  translations/sk.json
  utils/formatPrice.ts
  utils/formatPricePerHour.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#122 feat: #106 request parking cards
  .eslintrc.js
  app/parking-cards/enter-paas-account.tsx
  app/parking-cards/index.tsx
  app/purchase/index.tsx
  components/controls/notifications/NotificationSettings.tsx
  components/shared/Button.tsx
  modules/backend/openapi-generated/api.ts
  package.json
  translations/en.json
  yarn.lock
Labels: pr: fix & ship :ship:

#123 Map functionalities and active tickets
  components/map/Map.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  components/map/MapZoneBottomSheetAttachment.tsx
  components/shared/BottomSheetTopAttachment.tsx
  modules/map/hooks/useCameraChangeHandler.ts
  modules/map/hooks/useLocation.ts
  modules/map/utils/isWithinCityBounds.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#125 Get and display active tickets
  app/tickets/index.tsx
  app/zone-details/index.tsx
  assets/avatars/empty-state.svg
  assets/avatars/index.ts
  components/controls/ParkingZoneField.tsx
  components/controls/date-time/TimeSelector.tsx
  components/map/MapPointBottomSheet.tsx
  components/map/MapZoneBottomSheet.tsx
  components/map/MapZoneBottomSheetAttachment.tsx
  components/map/NavigateBottomSheetFooter.tsx
  components/tickets/TicketCard.tsx
  modules/backend/hooks/useTickets.ts
  modules/map/hooks/useProcessedMapData.ts
  modules/map/types.ts
  modules/map/utils/normalizeZone.ts
  state/GlobalStoreProvider.tsx
  state/hooks/useMapZone.ts
  state/types.ts
  translations/en.json
  translations/sk.json
  utils/formatDateTime.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#126 feature/#106: add and verify paas emails
  app/examples/bottom-sheet-example.tsx
  app/index.tsx
  app/parking-cards/[email].tsx
  app/parking-cards/enter-paas-account.tsx
  app/parking-cards/index.tsx
  app/parking-cards/verification-sent.tsx
  app/purchase/index.tsx
  components/actions/ListRow.tsx
  components/map/MapScreen.tsx
  components/navigation/ContinueButton.tsx
  components/parking-cards/EmailsBottomSheet.tsx
  components/parking-cards/ParkingCard.tsx
  components/parking-cards/base/ParkingCardBase.tsx
  components/parking-cards/cards/BonusCard.tsx
  components/parking-cards/cards/OtherCard.tsx
  components/parking-cards/cards/ResidentCard.tsx
  components/parking-cards/cards/SubscriberCard.tsx
  components/parking-cards/cards/VisitorCard.tsx
  components/shared/ScreenContent.tsx
  components/shared/ScreenView.tsx
  components/showcases/ParkingCardsShowcase.tsx
  modules/backend/hooks/useTickets.ts
  modules/backend/openapi-generated/api.ts
  modules/map/types.ts
  package.json
  state/types.ts
  translations/en.json
  translations/sk.json
  yarn.lock
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#133 Feat/#117 request price with npk
  app/index.tsx
  app/parking-cards/enter-paas-account.tsx
  app/parking-cards/verification-sent.tsx
  app/payment-methods/index.tsx
  app/purchase/choose-payment-method.tsx
  app/purchase/choose-vehicle.tsx
  app/purchase/index.tsx
  components/controls/payment-methods/MethodsField.tsx
  components/controls/payment-methods/PaymentMethodsFieldControl.tsx
  components/controls/payment-methods/VisitorCardMethod.tsx
  components/controls/payment-methods/VisitorCardsField.tsx
  components/map/MapScreen.tsx
  components/tickets/PurchaseBottomSheet.tsx
  modules/backend/openapi-generated/api.ts
  package.json
  translations/en.json
  translations/sk.json
  utils/formatPeriodOfTime.ts
  yarn.lock
Labels: pr: needs review :pray:

#134 Improve state management
  app/_layout.tsx
  app/auth.tsx
  app/confirm-signin.tsx
  app/confirm-signup.tsx
  app/purchase/choose-vehicle.tsx
  app/purchase/index.tsx
  app/tickets/index.tsx
  app/zone-details/index.tsx
  components/controls/ParkingZoneField.tsx
  components/controls/date-time/TimeSelector.tsx
  components/controls/payment-methods/MethodsField.tsx
  components/controls/payment-methods/PaymentGateMethod.tsx
  components/controls/payment-methods/PaymentMethodsFieldControl.tsx
  components/controls/payment-methods/VisitorCardsField.tsx
  components/controls/vehicles/VehicleRow.tsx
  components/map/Map.tsx
  components/map/MapAutocomplete.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheetAttachment.tsx
  components/shared/FlexRow.tsx
  components/shared/ScreenContent.tsx
  components/shared/ScreenView.tsx
  components/showcases/ButtonShowcase.tsx
  components/tickets/PurchaseBottomSheet.tsx
  components/tickets/TicketCard.tsx
  modules/map/hooks/useFilteredMapData.ts
  modules/map/hooks/useProcessedArcgisData.ts
  modules/map/types.ts
  modules/map/utils/normalizeZone.ts
  state/GlobalStoreProvider/GlobalStoreProvider.tsx
  state/GlobalStoreProvider/types.ts
  state/GlobalStoreProvider/useGlobalStoreContext.ts
  state/MapZonesProvider/MapZonesProvider.tsx
  state/MapZonesProvider/types.ts
  state/MapZonesProvider/useMapZone.ts
  state/MapZonesProvider/useMapZonesContext.ts
  state/MapZonesProvider/useMapZonesUpdateContext.ts
  state/hooks/useGlobalStoreContext.ts
  state/types.ts
  utils/formatPeriodOfTime.ts
Labels: pr: fix & ship :ship:

#137 Feat/#136 duration in second
  app/purchase/index.tsx
  components/controls/date-time/TimeSelector.tsx
  components/shared/Chip.tsx
  components/tickets/PurchaseBottomSheet.tsx
  components/tickets/getDurationFromPriceData.ts
  utils/formatDuration.ts
Labels: pr: needs review :pray:

#138 #130: Error messages
  app/_layout.tsx
  app/examples/snackbar.tsx
  components/DeveloperMenu.tsx
  components/actions/Snackbar.tsx
  components/special/AxiosResponseInterceptors.tsx
  hooks/useSnackbar.tsx
  modules/backend/hooks/useAxiosResponseInterceptors.ts
  package.json
  translations/en.json
  translations/sk.json
  yarn.lock
Labels: pr: needs review :pray:

#139 Overall improvements
  app/(purchase-and-payment)/_layout.tsx
  app/(purchase-and-payment)/payment-methods/index.tsx
  app/(purchase-and-payment)/purchase/choose-payment-method.tsx
  app/(purchase-and-payment)/purchase/choose-vehicle.tsx
  app/(purchase-and-payment)/purchase/index.tsx
  app/_layout.tsx
  app/parking-cards/[email].tsx
  app/parking-cards/index.tsx
  app/tickets/index.tsx
  components/controls/notifications/NotificationSettings.tsx
  components/controls/payment-methods/MethodsField.tsx
  components/controls/payment-methods/VisitorCardsField.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  components/map/MapZoneBottomSheetAttachment.tsx
  components/shared/ScreenView.tsx
  components/special/OmnipresentComponent.tsx
  modules/arcgis/constants.ts
  modules/arcgis/hooks/useArcgisData.ts
  modules/arcgis/hooks/useStaticArcgisData.ts
  modules/arcgis/types.ts
  modules/backend/axios-instance.ts
  modules/backend/constants/queryOptions.ts
  modules/backend/hooks/usePrefetchOnAppStart.tsx
  modules/backend/hooks/useTickets.ts
  modules/map/hooks/useProcessedArcgisData.ts
  package.json
  state/GlobalStoreProvider/GlobalStoreProvider.tsx
  state/PurchaseStoreProvider/PurchaseStoreProvider.tsx
  state/PurchaseStoreProvider/usePurchaseStoreContext.ts
  yarn.lock
Labels: pr: fix & ship :ship:

#145 use ScreenViewCentered in verification-sent.tsx
  app/parking-cards/verification-sent.tsx
  assets/avatars/email.svg
  assets/avatars/empty-state.svg
  assets/avatars/index.ts
  assets/avatars/parkovacia-karta.svg
  components/screen-layout/EmptyStateScreen.tsx
  components/screen-layout/ScreenViewCentered.tsx
  translations/en.json
  translations/sk.json
Labels: pr: needs review :pray:
