Repository bratislava/paas-mpa, pull requests merged in 2024-07, with the labels that each got.

#569 #555 Set react-query `retry` to 0
  app/_layout.tsx
Labels: pr: fix & ship :ship:

#572 #571 Hide visitor cards in prolongation when BPK was used for original ticket
  app/(app)/(purchase-and-payment)/prolongate/[ticketId]/choose-payment-method.tsx
  app/(app)/(purchase-and-payment)/prolongate/[ticketId]/index.tsx
  app/(app)/(purchase-and-payment)/purchase/index.tsx
  components/controls/payment-methods/UsedBonusCard.tsx
  components/tickets/ChoosePaymentMethodContent.tsx
Labels: pr: fix & ship :ship:

#573 #514 Use decimal point depending on locale
  app/(app)/zone-details.tsx
  components/controls/ParkingZoneField.tsx
  components/map/MapPin.tsx
  components/map/MapZoneBottomSheetPanel.tsx
  components/purchase/PurchaseSummaryRow.tsx
  components/tickets/PurchaseBottomSheet.tsx
  utils/formatPrice.ts
  utils/formatPriceForMapPin.ts
  utils/formatPricePerHour.ts
Labels: pr: fix & ship :ship:

#574 #374 Adjust parking cards list for better UX
  app/(app)/parking-cards/[email].tsx
Labels: pr: fix & ship :ship:

#581 #577 Fix `parkingStart` and `parkingEnd` to be sent rounded to minutes
  components/controls/date-time/TimeSelector.tsx
  utils/createPriceRequestBody.ts
Labels: pr: fix & ship :ship:

#582 Add production-testing profile
  eas.json
Labels: pr: fix & ship :ship:

#583 Change app runtime version to 1.2.1
  app.config.js
Labels: pr: fix & ship :ship:

#580 #575 Add interval to request price every minute
  app/(app)/(purchase-and-payment)/purchase/index.tsx
  modules/backend/axios-instance.ts
Labels: pr: fix & ship :ship:

#587 #585 Fix initial map zoom
  components/map/MapAutocomplete.tsx
  components/map/MapCamera.tsx
  modules/map/hooks/useLocation.ts
Labels: pr: fix & ship :ship:

#588 #584 Update wording on zoomed-out map bottom sheet
  translations/en.json
  translations/sk.json
Labels: pr: needs review :pray:

#596 #591 Remove leading zero in login value
  app/(auth)/sign-in/index.tsx
Labels: pr: fix & ship :ship:

#578 add link to product specification
  README.md
Labels: pr: fix & ship :ship:

#597 Private/#5: Fix notification settings after permissions are allowed
  modules/map/hooks/useNotificationPermission.ts
Labels: pr: fix & ship :ship:

#598 #557 Disallow to open purchase screen from planned zones
  components/map/MapZoneBottomSheet.tsx
  components/map/MapZoneBottomSheetPanel.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#600 #595 Add feedback message helptext
  app/(app)/feedback/index.tsx
  components/shared/Field.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#603 #536 Limit licence plate length to 15 characters
  app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
  app/(app)/vehicles/add-vehicle.tsx
Labels: pr: fix & ship :ship:

#602 #601 Use SectionList in Vehicles screen to fix collapsed text
  app/(app)/filters.tsx
  app/(app)/vehicles/index.tsx
  components/list-rows/SelectRow.tsx
Labels: pr: fix & ship :ship:

#599 #570 Add udr id and name to FreeTicket message
  components/purchase/PurchaseErrorPanel.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#606 #547 Hide error messages from payment gateway in FE
  components/purchase/PaymentStatus/ErrorContent.tsx
  components/purchase/PaymentStatus/PaymentStatusContent.tsx
Labels: pr: fix & ship :ship:

#607 #513 Add language to payment request to open paygate in user's locale
  app/(app)/(purchase-and-payment)/prolongate/[ticketId]/index.tsx
  app/(app)/(purchase-and-payment)/purchase/index.tsx
  utils/createPriceRequestBody.ts
  utils/getPaygateLanguageFromLocale.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#605 #586 Fix double map recenter when GPS enabled
  modules/map/hooks/useLocation.ts
  modules/map/hooks/useLocationPermission.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#604 #531 Temporary fix for BottomSheet to show also when ReducedMotion is on
  app/(app)/payment-options.tsx
  app/(app)/settings/index.tsx
  app/(app)/vehicles/index.tsx
  components/parking-cards/EmailsBottomSheet.tsx
  components/tickets/TicketsHistoryBottomSheet.tsx
Labels: pr: fix & ship :ship:

#608 #594 Add infobanner on android to check notifications permissions
  components/controls/notifications/NotificationSettings.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#611 #594 Request notification permission on Android
  app/permissions.tsx
  components/controls/notifications/NotificationSettings.tsx
  hooks/useSignInOrSignUp.ts
  modules/map/hooks/useNotificationPermission.ts
  utils/requestNotificationPermissionAsync.android.ts
  utils/types.ts
Labels: pr: fix & ship :ship:

#613 #612 Fix BottomSHeets when Reduced Motion enabled
  app/(app)/tickets/filters/timeframes.tsx
  components/map/MapLocationBottomSheet.tsx
  components/map/MapPointBottomSheet.tsx
  components/tickets/PurchaseBottomSheet.tsx
Labels: pr: fix & ship :ship:

#615 Upgrade runtime version to 1.2.2
  app.config.js
  package.json
Labels: pr: fix & ship :ship:
