Repository bratislava/paas-mpa, pull requests merged in 2024-01, with the labels that each got.

#340 navigate back to correct route from validation result page
  app/(app)/parking-cards/verification/verification-result.tsx
  components/controls/notifications/NotificationSettings.tsx
  modules/backend/constants/queryOptions.ts
Labels: pr: fix & ship :ship:

#339 Sprint 16 bug fixes
  app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
  app/(app)/filters/index.tsx
  app/(app)/tickets/filters/index.tsx
  app/(app)/tickets/filters/vehicles.tsx
  app/(app)/vehicles/add-vehicle.tsx
  assets/map/assistant.svg
  assets/map/images/assistant.png
  assets/map/images/index.ts
  assets/map/index.ts
  components/map/Map.tsx
  components/map/MapAutocomplete.tsx
  components/map/MapMarkers.tsx
  components/map/MapPointBottomSheet.tsx
  components/screen-layout/ScreenView.tsx
  components/screen-layout/StackScreenWithHeader.tsx
  components/tickets/ChoosePaymentMethodContent.tsx
  modules/arcgis/hooks/useArcgisData.ts
  modules/arcgis/hooks/useStaticArcgisData.ts
  modules/arcgis/types.ts
  modules/map/constants.ts
  modules/map/hooks/useProcessedArcgisData.ts
  modules/map/types.ts
  modules/map/utils/normalizePoint.ts
  modules/map/utils/processData.ts
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#343 lib checkbox to custom checkbox
  app/(app)/feedback/index.tsx
  app/(app)/search/index.tsx
  app/(app)/tickets/index.tsx
  app/(app)/tickets/shorten/index.tsx
  components/list-rows/SelectRow.tsx
  components/screen-layout/ScreenContent.tsx
  components/shared/CheckBox.tsx
  components/showcases/CheckBoxShowcase.tsx
  package.json
  yarn.lock
Labels: pr: fix & ship :ship:

#351 fix typo in EXPO_PUBLIC_MINIO_BUCKET env
  .env
Labels: pr: fix & ship :ship:

#360 Improvements language settings
  app/(app)/_layout.tsx
  app/(app)/announcements.tsx
  app/(app)/dev.tsx
  app/(app)/filters.tsx
  app/(app)/index.tsx
  app/(app)/payment-options.tsx
  app/(app)/search.tsx
  app/(app)/settings/index.tsx
  app/(app)/settings/language.tsx
  app/(app)/zone-details.tsx
  app/_layout.tsx
  app/onboarding.tsx
  app/permissions.tsx
  components/controls/LanguageSelect.tsx
  components/controls/LangugageSelectField.tsx
  components/controls/notifications/NotificationSettings.tsx
  components/map/MapZoneBottomSheetAttachment.tsx
  i18n.config.js
  modules/backend/constants/queryOptions.ts
  modules/backend/hooks/usePrefetchOnAppStart.tsx
  modules/backend/openapi-generated/api.ts
  state/AuthStoreProvider/AuthStoreProvider.tsx
  state/VehiclesStoreProvider/VehiclesStoreProvider.tsx
  translations/en.json
  translations/sk.json
  utils/languageDetectorPlugin.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#361 fix padding in Navigation Bottom Sheet
  app/permissions.tsx
  components/map/NavigateBottomSheetFooter.tsx
Labels: pr: fix & ship :ship:

#354 #321: Gis data aliases
  app/(app)/examples/bottom-sheet-example.tsx
  app/(app)/search.tsx
  app/(app)/zone-details.tsx
  components/controls/ParkingZoneField.tsx
  components/map/Map.tsx
  components/map/MapAutocomplete.tsx
  components/map/MapPointBottomSheet.tsx
  components/map/MapScreen.tsx
  components/map/MapZoneBottomSheet.tsx
  components/map/MapZoneBottomSheetPanel.tsx
  components/map/MapZones.tsx
  hooks/useTranslation.ts
  modules/arcgis/aliasedTypes.ts
  modules/arcgis/hooks/useArcgisData.ts
  modules/arcgis/hooks/useStaticArcgisData.ts
  modules/arcgis/types.ts
  modules/backend/constants/queryOptions.ts
  modules/map/hooks/useCameraChangeHandler.ts
  modules/map/hooks/useFilteredMapData.ts
  modules/map/hooks/useMapAutocompleteGetOptions.ts
  modules/map/hooks/useNormalizedPoint.ts
  modules/map/hooks/useProcessedArcgisData.ts
  modules/map/types.ts
  modules/map/utils/findShapesInRadius.ts
  modules/map/utils/forwardGeocode.ts
  modules/map/utils/layer-styles/visitors.ts
  modules/map/utils/normalizeAliasedPoint.ts
  modules/map/utils/normalizeAliasedZone.ts
  modules/map/utils/normalizePoint.ts
  modules/map/utils/normalizeZone.ts
  modules/map/utils/processData.ts
  modules/map/utils/reverseGeocode.ts
  modules/map/utils/translateMapObject.ts
  state/MapZonesProvider/useMapZone.ts
  state/PurchaseStoreProvider/PurchaseStoreProvider.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#362 #345: Weekend ticket prices
  app/(app)/zone-details.tsx
  components/controls/ParkingZoneField.tsx
  components/map/Map.tsx
  components/map/MapZoneBottomSheetPanel.tsx
  package.json
  translations/en.json
  translations/sk.json
  utils/getPriceFromZone.ts
  yarn.lock
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#381 Update sk.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#382 Update en.json
  translations/en.json
Labels: pr: fix & ship :ship:

#383 notification token exists check and permision screens checks
  app/permissions.tsx
  hooks/useSignInOrSignUp.ts
  modules/backend/constants/queryOptions.ts
  modules/map/hooks/useLocationPermission.ts
  modules/map/hooks/useNotificationPermission.ts
Labels: pr: fix & ship :ship:

#384 keep last selected language when logging out
  app/(app)/settings/language.tsx
  app/(auth)/confirm-sign-in.tsx
  components/controls/LangugageSelectField.tsx
  utils/changeUserLanguageToDevice.ts
Labels: pr: fix & ship :ship:

#392 Fix/ios gpay
  app/(app)/parking-cards/verification/verification-sent.tsx
  app/(app)/payment-options.tsx
  components/controls/payment-methods/PaymentOptionsField.tsx
  components/parking-cards/ParkingCard.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#389 debouncing duration
  app/(app)/(purchase-and-payment)/prolongate/[ticketId]/index.tsx
  app/(app)/(purchase-and-payment)/purchase/index.tsx
  utils/createPriceRequestBody.ts
Labels: pr: fix & ship :ship:

#385 cleanup dev files and display envs in dev environment
  .easignore
  .env
  .env.example
  app/(app)/(purchase-and-payment)/purchase/payment.tsx
  app/(app)/about/webview.tsx
  app/(app)/dev.tsx
  app/(app)/dev/examples/bottom-sheet-example.tsx
  app/(app)/dev/examples/codeinput-example.tsx
  app/(app)/dev/examples/empty-state-example.tsx
  app/(app)/dev/examples/healthcheck.tsx
  app/(app)/dev/examples/loaded-envs.tsx
  app/(app)/dev/examples/markdown-example.tsx
  app/(app)/dev/examples/modal-example.tsx
  app/(app)/dev/examples/snackbar-example.tsx
  app/(app)/dev/examples/styleguide.tsx
  app/(app)/dev/examples/user.tsx
  app/(app)/dev/index.tsx
  app/(app)/tickets/index.tsx
  eas.json
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#393 fix of double login bug
  app/onboarding.tsx
  hooks/useClearHistory.ts
  hooks/useSignInOrSignUp.ts
  modules/map/hooks/useLocation.ts
  modules/map/hooks/useNotificationPermission.ts
Labels: pr: fix & ship :ship:

#394 fix translations and onboarding screens order
  app/onboarding.tsx
  components/controls/payment-methods/PaymentMethodsFieldControl.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#387 Map docs
  .eslintrc.js
  components/map/Map.tsx
  components/map/MapMarkers.tsx
  components/map/MapZones.tsx
  docs/map.md
  modules/map/utils/layer-styles/markers.ts
  modules/map/utils/layer-styles/residents.ts
  modules/map/utils/layer-styles/visitors.ts
  modules/map/utils/layer-styles/zones.ts
Labels: pr: fix & ship :ship:

#396 android - open payment gateway in browser instead of webview
  app/(app)/(purchase-and-payment)/purchase/payment.tsx
Labels: pr: needs review :pray:

#395 go to center button
  app/(app)/(purchase-and-payment)/prolongate/[ticketId]/index.tsx
  app/(app)/(purchase-and-payment)/purchase/index.tsx
  app/(app)/search.tsx
  app/(app)/tickets/index.tsx
  components/inputs/Autocomplete.tsx
  components/map/MapAutocomplete.tsx
  components/map/MapZoneBottomSheetAttachment.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:

#401 increase app version to 1.0.6
  app.config.js
Labels: pr: fix & ship :ship:

#402 Improvement accessibility
  app/(app)/(purchase-and-payment)/purchase/choose-vehicle.tsx
  app/(app)/feedback/index.tsx
  app/(app)/parking-cards/verification/index.tsx
  app/(app)/vehicles/add-vehicle.tsx
  app/(auth)/confirm-sign-in.tsx
  app/onboarding.tsx
  components/controls/notifications/NotificationControl.tsx
  components/controls/notifications/SwitchControl.tsx
  components/inputs/CodeInput.tsx
  components/inputs/TextInput.tsx
  components/list-rows/SelectRow.tsx
  components/map/MapLocationBottomSheet.tsx
  components/map/MapZoneBottomSheet.tsx
  components/navigation/MarketingTabBar.tsx
  components/shared/AccessibilityField.tsx
  components/shared/CheckBox.tsx
  components/shared/Field.tsx
  components/shared/PressableStyled.tsx
  components/showcases/FieldShowcase.tsx
  components/showcases/SwitchShowcase.tsx
  translations/en.json
  translations/sk.json
Labels: pr: fix & ship :ship:
